plugins { id 'com.android.application' }

android {
    namespace 'com.hesbah.app'
    compileSdk 35

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId 'com.hesbah.app'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
        buildConfigField 'String', 'HESBAH_URL', '"https://hesbah-server.tail957349.ts.net/dashboard/"'
    }
}